In [3]:
import numpy as np

#Need to create matrix p
p = np.array([
    [0.9, 0.1, 0],
    [0, 0.75, 0.25],
    [0.5, 0, 0.5]
])

#Raise p^50
p_50 = np.linalg.matrix_power(p, 50)
print(p_50)

[[0.625 0.25  0.125]
 [0.625 0.25  0.125]
 [0.625 0.25  0.125]]
