In [4]:
import numpy as np

p = np.array([
    [0.5, 0.5, 0, 0, 0, 0],
    [1/3, 0, 1/3, 0, 1/3, 0],
    [0, 0, 0.25, 0.75, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0]
])

p_20 = np.linalg.matrix_power(p, 20)
p_21 = np.linalg.matrix_power(p, 21)

#Numbers weren't as nice the first time so I am going to round to 3 decimal places
print(np.round(p_20, decimals = 3))
print(np.round(p_21, decimals = 3))

[[0.001 0.001 0.285 0.213 0.312 0.187]
 [0.001 0.    0.285 0.215 0.062 0.437]
 [0.    0.    0.573 0.427 0.    0.   ]
 [0.    0.    0.57  0.43  0.    0.   ]
 [0.    0.    0.    0.    1.    0.   ]
 [0.    0.    0.    0.    0.    1.   ]]
[[0.001 0.001 0.285 0.214 0.187 0.312]
 [0.    0.    0.286 0.214 0.437 0.062]
 [0.    0.    0.57  0.43  0.    0.   ]
 [0.    0.    0.573 0.427 0.    0.   ]
 [0.    0.    0.    0.    0.    1.   ]
 [0.    0.    0.    0.    1.    0.   ]]
